name: gaussian_splatting_edit
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/object-feature-rasterization
    - submodules/flashsplat-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib